### ISSUE TITLE
Testing your project

### ISSUE THREAD

**Issue by CharlieNoodl** [VMarkos/prudens-js#1]
Hi,

I have been looking at your project and it is looking good.
However, testing is the key to prevent bugs from happening and I noticed you lack tests.
Here are a few recommendations:
- Test the function defined at the line 324 in the file prudens.js
- Test the function defined at the line 75 in the file utils.js
- Test the function defined at the line 167 in the file utils.js

I am working on a project called Ponicode, it is a VS Code extension that writes AI-generated unit tests. I think it could help you test your projects quickly.
It would be awesome if you could check it out on the VS Code Market Place, I would love to have some feedback.
Here is the link to the marketplace if you feel like trying it out: https://marketplace.visualstudio.com/items?itemName=ponicode.ponicode

Have a nice day,

Charlie.

**Comment by VMarkos** [comment]
Yeap, it is still under development. Especially, regarding `forwardChaining`, it is to be thoroughly refactored in the stable version. Thanks for mentioning your project, I will have a look at it! :)
